export const CREATE_CHECK_LIST: string = 'CREATE_CHECK_LIST';
export const OPEN_MODAL_FOR_CREATE_CHECK_LIST: string = 'OPEN_MODAL_FOR_CREATE_CHECK_LIST';
export const CLOSE_MODAL_FOR_CREATE_CHECK_LIST: string = 'CLOSE_MODAL_FOR_CREATE_CHECK_LIST';
export const EDITING_PERMISSION_POINT: string = 'EDITING_PERMISSION_POINT';
export const CHANGE_NAME_CHECK_LIST: string = 'CHANGE_NAME_CHECK_LIST';
export const MODAL_PERIOD_OPEN_CLOSE: string = 'MODAL_PERIOD_OPEN_CLOSE';
