export const STATISTICS_LOAD_LISTS: string = 'STATISTICS_LOAD_LISTS';
export const STATISTICS_LOAD_USERS: string = 'STATISTICS_LOAD_USERS';
export const STATISTICS_LOAD_POINTS: string = 'STATISTICS_LOAD_POINTS';
export const STATISTICS_CLEAR: string = 'STATISTICS_CLEAR';
export const LOAD_CHECK_LISTS_STATISTICS: string = 'LOAD_CHECK_LISTS_STATISTICS';