"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FILTER_HISTORY_TABLE = 'FILTER_HISTORY_TABLE';
exports.FILTER_CHECKLIST_LIST = 'FILTER_CHECKLIST_LIST';
exports.FILTER_INVITATIONS_LIST = 'FILTER_INVITATIONS_LIST';
exports.CLOSE_FILTER_HISTORY = 'CLOSE_FILTER_HISTORY';
exports.CLOSE_FILTER_CHECKLIST = 'CLOSE_FILTER_CHECKLIST';
exports.CLOSE_FILTER_INVITATIONS = 'CLOSE_FILTER_INVITATIONS';
