export const FILTER_HISTORY_TABLE: string = 'FILTER_HISTORY_TABLE';
export const FILTER_CHECKLIST_LIST: string = 'FILTER_CHECKLIST_LIST';
export const FILTER_INVITATIONS_LIST: string = 'FILTER_INVITATIONS_LIST';

export const CLOSE_FILTER_HISTORY: string = 'CLOSE_FILTER_HISTORY';
export const CLOSE_FILTER_CHECKLIST: string = 'CLOSE_FILTER_CHECKLIST';
export const CLOSE_FILTER_INVITATIONS: string = 'CLOSE_FILTER_INVITATIONS';
