export const PUBLIC_LIST_CHANGE_FILTER: string = 'PUBLIC_LIST_CHANGE_FILTER';
export const PUBLIC_LIST_CHANGE_PAGINATION: string = 'PUBLIC_LIST_CHANGE_PAGINATION';
export const PUBLIC_LIST_LOAD_LISTS: string = 'PUBLIC_LIST_LOAD_LISTS';