"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOAD_USERS_LIST_WITCH_SHARED_ACCESS = 'LOAD_USERS_LIST_WITCH_SHARED_ACCESS';
exports.CLEAR_SHARED_CHECK_LIST = 'CLEAR_SHARED_CHECK_LIST';
exports.SEND_SHARE_CHECK_LIST_FOR_USERS = 'SEND_SHARE_CHECK_LIST_FOR_USERS';
exports.PROVIDE_PUBLIC_ACCESS = 'PROVIDE_PUBLIC_ACCESS';
exports.LOADING_USERS_WHO_HAS_ACCESS = 'LOADING_USERS_WHO_HAS_ACCESS';
