"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.USER_AUTHORIZATION = 'USER_AUTHORIZATION';
exports.USER_SIGN_OUT = 'USER_SIGN_OUT';
exports.USER_AUTHORIZATION_TEST_PERIOD = 'USER_AUTHORIZATION_TEST_PERIOD';
exports.REDIRECT_DASHBOARD_FOR_LOGIN = 'REDIRECT_DASHBOARD_FOR_LOGIN';
exports.LOAD_USER_NAME = 'LOAD_USER_NAME';
