export const USER_AUTHORIZATION: string = 'USER_AUTHORIZATION';
export const USER_SIGN_OUT: string = 'USER_SIGN_OUT';
export const USER_AUTHORIZATION_TEST_PERIOD: string = 'USER_AUTHORIZATION_TEST_PERIOD';
export const REDIRECT_DASHBOARD_FOR_LOGIN: string = 'REDIRECT_DASHBOARD_FOR_LOGIN';
export const LOAD_USER_NAME: string = 'LOAD_USER_NAME';
export const SAVE_TOKEN: string = 'SAVE_TOKEN';