export const CREATE_CHECK_LIST: string = 'CREATE_CHECK_LIST';
export const OPEN_MODAL_FOR_CREATE_CHECK_LIST: string = 'OPEN_MODAL_FOR_CREATE_CHECK_LIST';
export const CLOSE_MODAL_FOR_CREATE_CHECK_LIST: string = 'CLOSE_MODAL_FOR_CREATE_CHECK_LIST';
export const EDITING_PERMISSION_POINT: string = 'EDITING_PERMISSION_POINT';
export const CHANGE_NAME_CHECK_LIST: string = 'CHANGE_NAME_CHECK_LIST';
export const MODAL_PERIOD_OPEN_CLOSE: string = 'MODAL_PERIOD_OPEN_CLOSE';

export const LOAD_MY_CHECK_LISTS: string = 'LOAD_MY_CHECK_LISTS';
export const DELETE_MY_CHECK_LISTS: string = 'DELETE_MY_CHECK_LISTS';
export const CLEAR_STATE_MY_CHECK_LIST: string = 'CLEAR_STATE_MY_CHECK_LIST';
export const MY_CHECK_LIST_LOADING: string = 'MY_CHECK_LIST_LOADING';
export const ADD_GEO_POINT_FROM_MY_POSITION: string = 'ADD_GEO_POINT_FROM_MY_POSITION';
export const LOAD_CHECK_LIST_DATA: string = 'LOAD_CHECK_LIST_DATA';
export const CLEAR_STATE_CHECK_LIST: string = 'CLEAR_STATE_CHECK_LIST';
export const LOAD_MARKERS_FOR_CHECK_LIST: string = 'LOAD_MARKERS_FOR_CHECK_LIST';