export const STATISTICS_LOAD_LISTS: string = 'STATISTICS_LOAD_LISTS';
export const STATISTICS_LOAD_USERS: string = 'STATISTICS_LOAD_USERS';
export const STATISTICS_LOAD_POINTS: string = 'STATISTICS_LOAD_POINTS';