export const STATISTICS_LOAD_LISTS: string = 'STATISTICS_LOAD_LISTS';
export const STATISTICS_LOAD_USERS: string = 'STATISTICS_LOAD_USERS';
export const STATISTICS_LOAD_POINTS: string = 'STATISTICS_LOAD_POINTS';
export const STATISTICS_CLEAR: string = 'STATISTICS_CLEAR';
export const STATISTICS_LOAD_FREE_CHECKS: string = 'STATISTICS_LOAD_FREE_CHECKS';
export const CLEAR_STATISTIC: string = 'CLEAR_STATISTIC';
export const PAGE_CHECK_IN_STATISTICS: string = 'PAGE_CHECK_IN_STATISTICS';