export const LOAD_LIST_HISTORY: string = 'LOAD_LIST_HISTORY';
export const SAVE_RECORD_HISTORY: string = 'SAVE_RECORD_HISTORY';
export const TABLE_HISTORY_LOADING: string = 'TABLE_HISTORY_LOADING';
export const CLEAR_TABLE_HISTORY: string = 'CLEAR_TABLE_HISTORY';