export const ADD_NOTIFICATION: string = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION: string = 'DELETE_NOTIFICATION';
export const DELETE_ALL_NOTIFICATIONS: string = 'DELETE_ALL_NOTIFICATIONS';