export const LOAD_USERS_LIST_WITCH_SHARED_ACCESS: string = 'LOAD_USERS_LIST_WITCH_SHARED_ACCESS';
export const CLEAR_SHARED_CHECK_LIST: string = 'CLEAR_SHARED_CHECK_LIST';
export const SEND_SHARE_CHECK_LIST_FOR_USERS: string = 'SEND_SHARE_CHECK_LIST_FOR_USERS';
export const PROVIDE_PUBLIC_ACCESS: string = 'PROVIDE_PUBLIC_ACCESS';