export const USER_AUTHORIZATION: string = 'USER_AUTHORIZATION';
export const USER_SIGN_OUT: string = 'USER_SIGN_OUT';
export const USER_AUTHORIZATION_TEST_PERIOD: string = 'USER_AUTHORIZATION_TEST_PERIOD';